# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\fss\review.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_review(object):
    def setupUi(self, review):
        review.setObjectName("review")
        review.resize(400, 300)
        self.Confirm = QtWidgets.QPushButton(review)
        self.Confirm.setGeometry(QtCore.QRect(80, 270, 75, 23))
        self.Confirm.setObjectName("Confirm")
        self.Enter = QtWidgets.QTextEdit(review)
        self.Enter.setGeometry(QtCore.QRect(10, 10, 371, 251))
        self.Enter.setObjectName("Enter")
        self.Cancle = QtWidgets.QPushButton(review)
        self.Cancle.setGeometry(QtCore.QRect(220, 270, 75, 23))
        self.Cancle.setObjectName("Cancle")

        self.retranslateUi(review)
        self.Cancle.clicked.connect(QCoreApplication.instance().quit)
        self.Confirm.clicked.connect(review.ConfirmClicked)
        self.Cancle.clicked.connect(review.CancelClicked)
        QtCore.QMetaObject.connectSlotsByName(review)

    def retranslateUi(self, review):
        _translate = QtCore.QCoreApplication.translate
        review.setWindowTitle(_translate("review", "影评"))
        self.Confirm.setText(_translate("review", "确认"))
        self.Cancle.setText(_translate("review", "取消"))
